//@version=4
// set05 corpus entry
// source_repo: hasnocool-tradingview-pine-scripts
// source_path: hasnocool-tradingview-pine-scripts/Patron04 TOFF MACD DEMA Strategy.pine
// content_hash: 6f2ff0188a02e1ff
// collected: 2026-07-27
strategy(title="Patron04 MACD DEMA TOFF Stategy",default_qty_type = strategy.percent_of_equity,default_qty_value = 3500, commission_value=0.075, overlay=true)
testStartYear = input(2000, "Backtest Start Year") 
testStartMonth = input(1, "Backtest Start Month")
testStartDay = input(1, "Backtest Start Day")
testPeriodStart = timestamp(testStartYear,testStartMonth,testStartDay,0,0)
testStopYear = input(2100, "Backtest Stop Year")
testStopMonth = input(12, "Backtest Stop Month")
testStopDay = input(31, "Backtest Stop Day")
testPeriodStop = timestamp(testStopYear,testStopMonth,testStopDay,0,0)
testPeriod() =>
    time >= testPeriodStart and time <= testPeriodStop ? true : false
sma = input(12,title='DEMA Courte')
lma = input(26,title='DEMA Longue')
tsp = input(9,title='Signal')
dolignes = input(true,title="Lignes")
MMEslowa = ema(close,lma)
MMEslowb = ema(MMEslowa,lma)
DEMAslow = ((2 * MMEslowa) - MMEslowb )
MMEfasta = ema(close,sma)
MMEfastb = ema(MMEfasta,sma)
DEMAfast = ((2 * MMEfasta) - MMEfastb)
LigneMACDZeroLag = (DEMAfast - DEMAslow)
MMEsignala = ema(LigneMACDZeroLag, tsp)
MMEsignalb = ema(MMEsignala, tsp)
Lignesignal = ((2 * MMEsignala) - MMEsignalb )
MACDZeroLag = (LigneMACDZeroLag - Lignesignal)
a = input(title="Long Value", type=input.integer, defval=0)
b = input(title="Short Value", type=input.integer, defval=0)
long = crossover(LigneMACDZeroLag, a)
short = crossunder(LigneMACDZeroLag, b)
if testPeriod()
    strategy.entry("Long", strategy.long,when=long)
    strategy.entry("Short", strategy.short,when=short)
Expand (75 lines)
