//@version=4
// set05 corpus entry
// source_repo: hasnocool-tradingview-pine-scripts
// source_path: hasnocool-tradingview-pine-scripts/Logistic strategy.pine
// content_hash: 9de263f68bd93c8b
// collected: 2026-07-27
strategy("Logistic", overlay=true, shorttitle="Logistic Strategy", default_qty_type= strategy.percent_of_equity, default_qty_value= 100, initial_capital= 10000, calc_on_every_tick=true)
volume_pos = 0.0
volume_neg = 0.0
roc = roc(close, 1)
for i = 0 to 100
    if (roc > 0)
        volume_pos := volume
    else
        volume_neg := volume
    
volume_net = volume_pos - volume_neg
net_std    = stdev(volume_net, 100)
net_sma    = sma(volume_net, 10)
z          =  net_sma / net_std
std        = stdev(close, 20)
logistic(close, std, z) =>
    m = (close + std)
    a = std / close
    pt = m / ( 1 + a*exp(-z))
    pt
    
    
pred = logistic(close, std, z)
buy = pred > close * 1.005
sell = pred < close * 0.995
color = strategy.position_size > 0? #3BB3E4 : strategy.position_size == 0? #FF006E : #6b6b6b
barcolor(color)
if (buy == true)
    strategy.entry("Long", strategy.long, comment="Open L")
    
if (sell == true)
    strategy.close("Long", comment="Close L")
Expand (41 lines)
