//@version=4
// set05 corpus entry
// source_repo: hasnocool-tradingview-pine-scripts
// source_path: hasnocool-tradingview-pine-scripts/Ichimoku Cloud Strategy v2.0.pine
// content_hash: 07d6187e26890ae1
// collected: 2026-07-27
strategy("Ichimoku Cloud Strategy v2.0", overlay=true)
//@version=4
// study(title="Ichimoku Cloud", shorttitle="Ichimoku", overlay=true)
conversionPeriods = input(9, minval=1, title="Conversion Line Periods"),
basePeriods = input(26, minval=1, title="Base Line Periods")
laggingSpan2Periods = input(52, minval=1, title="Lagging Span 2 Periods"),
displacement = input(26, minval=1, title="Displacement")
donchian(len) => avg(lowest(len), highest(len))
conversionLine = donchian(conversionPeriods)
baseLine = donchian(basePeriods)
leadLine1 = avg(conversionLine, baseLine)
leadLine2 = donchian(laggingSpan2Periods)
plot(conversionLine, color=#0496ff, title="Conversion Line")
plot(baseLine, color=#991515, title="Base Line")
plot(close, offset = -displacement + 1, color=#459915, title="Lagging Span")
p1 = plot(leadLine1, offset = displacement - 1, color=color.green,
 title="Lead 1")
p2 = plot(leadLine2, offset = displacement - 1, color=color.red, 
 title="Lead 2")
fill(p1, p2, color = leadLine1 > leadLine2 ? color.green : color.red)
// Strategy
longCondition = crossover(conversionLine,baseLine)
if (longCondition)
    strategy.entry("Buy", strategy.long)
shortCondition = crossover(baseLine, conversionLine)
if (shortCondition)
    strategy.entry("Short", strategy.short)
Expand (41 lines)
