//@version=4
// set05 corpus entry
// source_repo: hasnocool-tradingview-pine-scripts
// source_path: hasnocool-tradingview-pine-scripts/Сalculation a position size based on risk.pine
// content_hash: 8cea5656b7f6e49e
// collected: 2026-07-27
strategy("Сalculation a position size based on risk", overlay=true, margin_long=10, margin_short=10, currency = currency.NONE)
percent2points(percent) =>
    strategy.position_size !=0 ? strategy.position_avg_price * percent / 100 / syminfo.mintick : na
percent2money(price, percent) =>
    price * percent / 100 * syminfo.pointvalue
    
slPcnt = input(10, title = "Stop Loss %%")
riskValue = input(2, title="Risk ", inline="risk", tooltip="Max risk for position")
riskType = input("% from equity", title="", options=["% from equity", "$$"], inline="risk")
calcPositionSize(entryPrice, slPercent) =>
    risk = if riskType == "% from equity"
        strategy.equity * riskValue / 100
    else
        riskValue
    risk / percent2money(entryPrice, slPercent)
qty = calcPositionSize(close, slPcnt)
// random entry 
longCondition = bar_index % 333 == 0
if (longCondition)
    strategy.entry("My Long Entry Id", strategy.long, qty = qty)
shortCondition = bar_index % 444 == 0
if (shortCondition)
    strategy.entry("My Short Entry Id", strategy.short, qty = qty)
// exit with stop loss
slPts = percent2points(slPcnt)
strategy.exit("x", loss = slPts)
Expand (43 lines)
