//@version=4
// set05 corpus entry
// source_repo: hasnocool-tradingview-pine-scripts
// source_path: hasnocool-tradingview-pine-scripts/Bollinger bubble - Stock Edition.pine
// content_hash: 6ecae823067b5723
// collected: 2026-07-27
// Initial settings
strategy("Bulle de bollinger", overlay = true, currency = currency.EUR, initial_capital = 10000, default_qty_type = strategy.percent_of_equity, default_qty_value = 100, commission_type = strategy.commission.percent, commission_value = 0)
// Parameter Settings
mdl = sma(close, 20)
dev = stdev(close, 20)
upr = mdl + 2*dev
lwr = mdl - 2*dev
// Plot
plot(mdl, color = color.red) // Plot moving average
p1 = plot(upr, color = color.green) // Plot Upper_band
p2 = plot(lwr, color = color.green) // Plot lower band
fill(p1, p2, color = color.blue) // Fill transparant color between the 2 plots
// Strategy entry & close
if open[1] < lwr[1] and close[0] > low[0] // Previous price lower than lower band and current close is higher than lower band
    stop_level = lowest(100)
    profit_level = highest(20)
    strategy.entry(id = 'bb_buy', long = true)
    strategy.exit("TP/SL", "bb_buy", stop=stop_level, limit=profit_level)
Expand (25 lines)
