//@version=4
// set05 corpus entry
// source_repo: hasnocool-tradingview-pine-scripts
// source_path: hasnocool-tradingview-pine-scripts/Consecutive Up-Down Strat + alerts via TradingConnector to Forex.pine
// content_hash: e281eedd6665d87c
// collected: 2026-07-27
strategy("Consecutive Up/Down Strategy with alerts via TradingConnector to Forex", overlay=true, default_qty_value=1000)
consecutiveBarsUp = input(3)
consecutiveBarsDown = input(3)
price = close
ups = 0.0
ups := price > price[1] ? nz(ups[1]) + 1 : 0
dns = 0.0
dns := price < price[1] ? nz(dns[1]) + 1 : 0
if (ups >= consecutiveBarsUp)
    strategy.entry("ConsUpLE", strategy.long, comment="ConsUpLE")
    alert(message='long', freq=alert.freq_once_per_bar_close)
if (dns >= consecutiveBarsDown)
    strategy.entry("ConsDnSE", strategy.short, comment="ConsUpLE")
    alert(message='short', freq=alert.freq_once_per_bar_close)
//plot(strategy.equity, title="equity", color=color.red, linewidth=2, style=plot.style_areabr)
//Lines of code added to the original built-in script: 12 and 15 only.
//They trigger alerts ready to be executed on real markets through TradingConnector
//available for Forex, indices, crypto, stocks - anything your broker offers for trading via MetaTrader4/5
Expand (21 lines)
