//@version=4
// set05 corpus entry
// source_repo: fmzquant-strategies
// source_path: fmzquant-strategies/RSI拉升突破策略RSI-Breakout-Strategy.md
// content_hash: 1ce9d356765051b3
// collected: 2026-07-27
strategy(title="HiLoExtn", shorttitle="HiLoExtn", overlay=true)


T1 = time(timeframe.period, "0915-0916")
Y = bar_index
Z1 = valuewhen(T1, bar_index, 0)
L = Y-Z1 + 1

tim = time(timeframe.period, "1015-1510")
exitt= time(timeframe.period, "1511-1530")

//VWMA 20
plot(vwma(close,20), color=color.blue)


length = L
lower = lowest(length)
upper = highest(length)
u = plot(upper, "Upper", color=color.green)
l = plot(lower, "Lower", color=color.red)


//**** RSI
len = 14
src = close
up = rma(max(change(src), 0), len)
down = rma(-min(change(src), 0), len)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))




// Buy above Buy Line
if ( (upper==high) and rsi>50 and   tim and close>open )
    strategy.entry("Buy", strategy.long, comment="Buy")
    
// Exit Long Below Vwap
strategy.close("Buy", when = close < vwma(close,20) or exitt) 

// Sell above Buy Line
if ((lower==low) and rsi<50 and   tim  and close<open)
    strategy.entry("Sell", strategy.short, comment="Sell")
    
// Exit Short above Vwap    
strategy.close("Sell", when = close > vwma(close,20) or exitt)



```

> Detail

https://www.fmz.com/strategy/434977

> Last Modified

2023-12-11 14:34:54
