//@version=4
// set05 corpus entry
// source_repo: fmzquant-strategies
// source_path: fmzquant-strategies/RSI趋势追踪型加密货币策略RSI-Trend-Following-Crypto-Strategy.md
// content_hash: 5d20e239349ded4e
// collected: 2026-07-27
strategy("RSI Trend Crypto", overlay=false, pyramiding=1, commission_value=0.2, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

// Input
UseEmergency = input(false, "Use Emergency Exit?")
RSIlong = input(35, "RSI Long Cross")
RSIclose = input(75, "RSI Close Position")
Emergencyclose = input(10, "RSI Emergency Close Position")

// RSI
rsi = rsi(close, 14)

// Conditions
long = crossover(rsi, RSIlong)
longclose = crossunder(rsi, RSIclose)
emergency = crossunder(rsi, Emergencyclose)

// Plots
plot(rsi, color=color.white, linewidth=2)
plot(RSIlong, color=color.green)
plot(RSIclose, color=color.red)

// Alert messages 
// When using a bot remember to use "{{strategy.order.alert_message}}" in your alert
// You can edit the alert message freely to suit your needs

LongAlert = 'RSI Long Cross: LONG'
CloseAlert = 'RSI Close Position'
EmergencyAlert = 'RSI Emergency Close'

// Strategy
if long
    strategy.entry("Long", strategy.long, alert_message=LongAlert)

if longclose
    strategy.close("Long", alert_message=CloseAlert)

if emergency and UseEmergency==true
    strategy.close("Long", alert_message=EmergencyAlert)










```

> Detail

https://www.fmz.com/strategy/435146

> Last Modified

2023-12-12 16:26:49
