//@version=3
// set05 corpus entry
// source_repo: fmzquant-strategies
// source_path: fmzquant-strategies/突破拉回中的隐形风暴Breakback-Storm-Strategy-in-Hidden-Opportunities.md
// content_hash: e8575f3136950cb2
// collected: 2026-07-27
strategy("Smash Day Pattern (Type B)", overlay=true, default_qty_type = strategy.fixed, default_qty_value = 1, initial_capital = 10000)
in1 = input(40, "Max Days to Hold") - 1

isLong = strategy.position_size > 0
isShort = strategy.position_size < 0

longTrigger = close[1]<low[2]
shortTrigger = close[1]>high[2]

longFilter = close[1] > close[80]
shortFilter = close[1] < close[80]

longEntry = (not isLong) and longTrigger and longFilter
shortEntry = (not isShort) and shortTrigger and shortFilter

longStop = valuewhen(longEntry, low[1], 0)
longPrice = valuewhen(longEntry, high[1], 0)
shortStop = valuewhen(shortEntry, high[1],0)
shortPrice = valuewhen(shortEntry, low[1], 0)

strategy.entry(id = "Long", long = true, stop = longPrice+.001, when = longEntry)
strategy.exit(id = "Stop Long", from_entry = "Long", stop = longStop, when = isLong)
strategy.close("Long", barssince(longEntry==true)>=in1)

strategy.entry(id = "Short", long = false, stop = shortPrice-.001, when = shortEntry)
strategy.exit(id = "Stop Short", from_entry = "Short", stop = shortStop, when = isShort)
strategy.close("Short", barssince(shortEntry==true)>=in1)
```

> Detail

https://www.fmz.com/strategy/440678

> Last Modified

2024-02-01 10:25:35
