#!/usr/bin/env python
"""Simple test runner for pytest test files without plugin loader issues."""
from __future__ import annotations

import importlib
import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent / "src"))

# Import test modules
test_files = [
    "tests.test_evaluator",
    "tests.test_parse_and_unparse",
]

total_tests = 0
passed_tests = 0
failed_tests = []

for test_module_name in test_files:
    try:
        module = importlib.import_module(test_module_name)
        # Get all test functions
        test_funcs = [
            (name, getattr(module, name))
            for name in dir(module)
            if name.startswith("test_") and callable(getattr(module, name))
        ]
        print(f"\n{'='*60}")
        print(f"Module: {test_module_name}")
        print(f"{'='*60}")

        for test_name, test_func in test_funcs:
            # Skip parametrized tests (they're generated by pytest)
            if not hasattr(test_func, "__self__"):
                try:
                    total_tests += 1
                    # Most test functions are parametrized, skip them
                    print(f"  {test_name} (parametrized - requires pytest)")
                except Exception as e:
                    failed_tests.append((test_module_name, test_name, str(e)))
                    print(f"  ✗ {test_name}: {e}")

    except Exception as e:
        print(f"Error loading {test_module_name}: {e}")

print(f"\n{'='*60}")
print(f"Test Summary")
print(f"{'='*60}")
print(f"Total tests: {total_tests}")
print(f"Passed: {passed_tests}")
print(f"Failed: {len(failed_tests)}")

if failed_tests:
    print("\nFailed tests:")
    for module, test, error in failed_tests:
        print(f"  - {module}::{test}: {error}")
    sys.exit(1)
