#!/usr/bin/env python3
"""
Python → TypeScript skeleton converter (porting aid).

Part of pine-worker (the TypeScript port / extra tool in the pynescript repo).

Usage examples:
    python pine-worker/scripts/convert-python-to-ts.py \
        src/pynescript/ast/evaluator/builtins/numeric.py > pine-worker/src/evaluator/builtins/numeric.ts

    python pine-worker/scripts/convert-python-to-ts.py \
        --namespace technical --module src/pynescript/ast/evaluator/builtins/technical.py

It produces a starting .ts file with:
- imports
- function signatures turned into TS
- JSDoc from Python docstrings (best-effort)
- TODO markers for body porting

This is **not** a full automatic translator. The port still requires manual
implementation to match Python semantics exactly (see parity tests).
The goal is to reduce boilerplate when porting the 100+ builtin functions.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys

from pathlib import Path
from textwrap import indent


def py_to_ts_type(py_annotation: str | None) -> str:
    if not py_annotation:
        return "any"
    ann = py_annotation.strip()
    mapping = {
        "int": "number",
        "float": "number",
        "str": "string",
        "bool": "boolean",
        "list": "any[]",
        "List": "any[]",
        "dict": "Record<string, any>",
        "Dict": "Record<string, any>",
        "tuple": "any[]",
        "Any": "any",
        "Optional": "any | null",
        "Union": "any",
        "None": "null",
    }
    for k, v in mapping.items():
        ann = re.sub(rf"\b{k}\b", v, ann)
    # crude: drop generics etc.
    ann = re.sub(r"\[.*?\]", "", ann)
    return ann or "any"


def extract_docstring(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    if (
        node.body
        and isinstance(node.body[0], ast.Expr)
        and isinstance(node.body[0].value, (ast.Constant, ast.Str))
    ):
        val = node.body[0].value
        if isinstance(val, ast.Constant) and isinstance(val.value, str):
            return val.value.strip()
        if isinstance(val, ast.Str):
            return val.s.strip()
    return ""


def convert_function(node: ast.FunctionDef, _namespace: str) -> str:
    name = node.name
    args = []
    for arg in node.args.args:
        ann = None
        if arg.annotation:
            try:
                ann = ast.unparse(arg.annotation) if hasattr(ast, "unparse") else None
            except Exception:
                ann = None
        ts_type = py_to_ts_type(ann)
        args.append(f"{arg.arg}: {ts_type}")

    # crude return annotation
    ret_ann = None
    if node.returns:
        try:
            ret_ann = ast.unparse(node.returns) if hasattr(ast, "unparse") else None
        except Exception:
            ret_ann = None
    ret_type = py_to_ts_type(ret_ann)

    doc = extract_docstring(node)
    jsdoc = ""
    if doc:
        # simple escape
        doc_lines = "\n * ".join(doc.splitlines())
        jsdoc = f"/**\n * {doc_lines}\n */\n"

    sig = f"function {name}({', '.join(args)}): {ret_type} {{"
    body = (
        "  // TODO: port implementation from Python (must match parity fixtures)\n"
        "  throw new Error('not implemented');\n"
    )

    return f"{jsdoc}export {sig}\n{body}\n"


def convert_file(py_path: Path, namespace: str | None = None) -> str:
    source = py_path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(py_path))

    ns = namespace or py_path.stem

    header = f"""// ---------------------------------------------------------------------------
// {ns} — ported from {py_path}
// This file was initially generated by convert-python-to-ts.py (skeleton only).
// Manual implementation + parity verification required.
// See pynescript/src/pynescript/ast/evaluator/builtins/{ns}.py
// ---------------------------------------------------------------------------

import {{ NA }} from "../types";

"""

    funcs: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name.startswith("_"):
                continue
            funcs.append(convert_function(node, ns))

    if not funcs:
        funcs.append("// No public top-level functions detected.\n")

    registry = f"""
// Registry helper (adapt to your BuiltinRegistry pattern)
export const {ns} = {{
{indent(
    chr(10).join(
        f"  {f.split('(')[0].split()[-1]}: {f.split('(')[0].split()[-1]},"
        for f in funcs
        if "function " in f
    ),
    "  ",
)}
}};
"""

    return header + "\n".join(funcs) + "\n" + registry


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate TS skeleton from Python builtin module.")
    parser.add_argument("py_file", type=Path, help="Path to .py file to convert (e.g. a builtins/*.py)")
    parser.add_argument("--namespace", "-n", help="Override namespace name (default: filename stem)")
    parser.add_argument("--out", "-o", type=Path, help="Write to this .ts file instead of stdout")
    args = parser.parse_args()

    py_path: Path = args.py_file
    if not py_path.exists():
        print(f"ERROR: {py_path} not found", file=sys.stderr)  # noqa: T201
        sys.exit(1)

    ts_code = convert_file(py_path, args.namespace)

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(ts_code, encoding="utf-8")
        print(f"Wrote skeleton to {args.out}")  # noqa: T201
    else:
        print(ts_code)  # noqa: T201


if __name__ == "__main__":
    main()
