// set04 corpus entry
// source_repo: QuanTAlib
// source_path: QuanTAlib/lib/numerics/exptrans/exptrans.pine
// content_hash: 362e72a3b12bad6b
// collected: 2026-07-27
// Licensed under the Apache License, Version 2.0
// © mihakralj
//@version=6
indicator("Exponential Transformation (EXP)", "Exptrans", overlay=false)

//@function Applies an exponential transformation (y = e^x) to the input series.
//@param source series float The input series to transform.
//@returns series float The exponentially transformed series.
//@optimized for performance and dirty data
expT(series float source) =>
    if na(source)
        na
    else
        math.exp(source)

// ---------- Main loop ----------

// Inputs
i_source = input.source(close, "Source")

// Calculation
transformedSource = expT(i_source)

// Plot
plot(transformedSource, "Exptrans", color=color.yellow, linewidth=2)
