// set04 corpus entry
// source_repo: mihakralj-pinescript
// source_path: mihakralj-pinescript/indicators/core/ha.pine
// content_hash: 8d9bafb32cc4a798
// collected: 2026-07-27
// The MIT License (MIT)
// © mihakralj
//@version=6
indicator("HA: Heikin-Ashi", overlay=true)

var float haOpen  = na
var float haClose = na

haClose := (open + high + low + close) * 0.25
haOpen  := na(haOpen) ? (open + close) * 0.5 : (haOpen + haClose[1]) * 0.5
haHigh   = math.max(high, haOpen, haClose)
haLow    = math.min(low,  haOpen, haClose)

plotcandle(haOpen, haHigh, haLow, haClose, "HA", color=haClose >= haOpen ? color.green : color.red)
