// set04 corpus entry
// source_repo: mihakralj-pinescript
// source_path: mihakralj-pinescript/indicators/core/avgprice.pine
// content_hash: f4f7e859d08001ea
// collected: 2026-07-27
// The MIT License (MIT)
// © mihakralj
//@version=6
indicator("AVGPRICE: Average Price", overlay=true)

avgprice(float o, float h, float l, float c) =>
    (o + h + l + c) * 0.25

result = avgprice(open, high, low, close)

plot(result, "AvgPrice", color.new(color.blue, 0), 2)
