//@version=6
// set04 corpus entry
// source_repo: pinescriptv6
// source_path: pinescriptv6/pinescriptv6_complete_reference.md::pinescriptv6_complete_reference.md#block343
// content_hash: 6bfb977f9cf045c7
// collected: 2026-07-27
indicator("[]")
// [] can be used to "save" variable value between bars
a = 0.0 // declare `a`
a := a[1] // immediately set current value to the same as previous. `na` in the beginning of history
if high == low // if some condition - change `a` value to another
    a := low
plot(a)
