//@version=5
// set05 corpus entry
// source_repo: fmzquant-strategies
// source_path: fmzquant-strategies/Simple-Buy-Sell-Signals.md
// content_hash: ce201beda90066f9
// collected: 2026-07-27
indicator("Simple Buy Sell Signals",overlay=true,format=format.price,shorttitle="SBS")

[dp,dm,adx]  =ta.dmi(14,14)

rsi = ta.rsi(close,9)
rsiOB = rsi > 60 and not(rsi[1] < 40)
rsiOS = rsi < 40 and not(rsi[1] > 60)

ma1 = math.avg(ta.sma(close,21),ta.ema(close,50))
ma2 = ta.ema(close,35)

nmL = ta.crossover(ma1,ma2) and rsiOB
nmS = ta.crossover(ma1,ma2) and rsiOS

plotshape(nmL ? nmL : 0,title="Long",style=shape.labelup,text="Buy",textcolor=color.white,color=color.aqua,location=location.belowbar)
plotshape(nmS ? nmS : 0,title="Short",style=shape.labeldown,text="Sell",textcolor=color.white,color=color.orange,location=location.abovebar)

// plot(ma1,color=color.green,linewidth=4)
// plot(ma2,color=color.red,linewidth=4)

//Strategy Tester
if nmL 
    strategy.entry("Enter Long", strategy.long)
else if nmS
    strategy.entry("Enter Short", strategy.short)
// strategy.close("Long",when=nmS)
// strategy.close("Short",when=nmL)
```

> Detail

https://www.fmz.com/strategy/380396

> Last Modified

2022-08-28 18:30:25
