//@version=3
// set05 corpus entry
// source_repo: tradingview-custom-indicators
// source_path: tradingview-custom-indicators/oscillators/volatility_ratio.pine
// content_hash: 4f65733cf2c5e897
// collected: 2026-07-27
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Volatility Ratio script may be freely distributed under the MIT license.
study("Volatility Ratio", shorttitle="VR")

length = input(title="Length", type=integer, minval=1, defval=14)
breakoutLevel = input(title="Breakout Level", type=float, step=0.1, defval=0.5)

max = max(highest(high, length), close[length + 1])
min = min(lowest(low, length), close[length + 1])

vr = tr(true) / (max - min)

vrColor = vr >= breakoutLevel ? #39b361 : #cc4125

plot(vr, title="VR", linewidth=2, color=vrColor, transp=0)

hline(title="Breakout Level", price=breakoutLevel, linestyle=dotted, color=gray)
