//@version=3
// set05 corpus entry
// source_repo: tradingview-custom-indicators
// source_path: tradingview-custom-indicators/movings/moving_harmonic_mean.pine
// content_hash: 54065beeab2c762b
// collected: 2026-07-27
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Moving Harmonic Mean script may be freely distributed under the MIT license.
study("Moving Harmonic Mean", shorttitle="MHM", overlay=true)

length = input(title="Length", type=integer, defval=14, minval=1)
src = input(title="Source", type=source, defval=close)

mhm(src, length) =>
	sum = 0.0

	for i = 0 to length - 1
		sum := sum + 1 / (na(src[i]) ? 1 : src[i])

	length / sum

plot(mhm(src, length), title="MHM", linewidth=2, color=#6d1e7f, transp=0)
