//@version=3
// set05 corpus entry
// source_repo: tradingview-custom-indicators
// source_path: tradingview-custom-indicators/movings/recursive_moving_trend_average.pine
// content_hash: 7d867189a3784c4c
// collected: 2026-07-27
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Recursive Moving Trend Average script may be freely distributed under the MIT license.
study("Recursive Moving Trend Average", shorttitle="RMTA", overlay=true)

length = input(title="Length", type=integer, minval=1, defval=14)
src = input(title="Source", type=source, defval=close)

alpha = 2 / (length + 1)

b = 0.0
b := (1 - alpha) * nz(b[1], src) + src

rmta = 0.0
rmta := (1 - alpha) * nz(rmta[1], src) + alpha * (src + b - nz(b[1]))

plot(rmta, title="RMTA", linewidth=2, color=#6d1e7f, transp=0)
