//@version=3
// set05 corpus entry
// source_repo: tradingview-custom-indicators
// source_path: tradingview-custom-indicators/indicators/CloudyMomentum.pine
// content_hash: 9f7218780cb9c81b
// collected: 2026-07-27
study(title="Cloudy Momentum", shorttitle="Cloudy Momentum", overlay=true)
length = input(26, minval=1)
emaLength = input(55)
lower = lowest(close, length) - (highest(close, length)-lowest(close, length))*0.618
upper = highest(close, length) + (highest(close, length)-lowest(close, length))*0.618

lowerEMA = ema(lower,emaLength)
upperEMA = ema(upper,emaLength)
basis = avg(lowerEMA, upperEMA)

lEMA = plot(lowerEMA, offset = emaLength, color=blue)
uEMA = plot(upperEMA, offset = emaLength, color=blue)
plot(basis, offset = emaLength, color=orange)

fill(lEMA, uEMA, color=blue)
