//@version=3
// set05 corpus entry
// source_repo: tradingview-custom-indicators
// source_path: tradingview-custom-indicators/movings/infinite_impulse_response_filter.pine
// content_hash: 47096f65853b7b6d
// collected: 2026-07-27
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Infinite Impulse Response (IIR) Filter script may be freely distributed under the MIT license.
study("Infinite Impulse Response (IIR) Filter", shorttitle="IIRF", overlay=true)

length = input(title="Length", type=integer, defval=14, minval=1)
src = input(title="Source", type=source, defval=close)

iirfAlpha = 2 / (length + 1)

iirfLag = round((1 / iirfAlpha) - 1)

iirf = 0.0
iirf := iirfAlpha * (src + change(src, iirfLag)) + (1 - iirfAlpha) * nz(iirf[1])

plot(iirf, title="IIRF", linewidth=2, color=#6d1e7f, transp=0)
