//@version=3
// set05 corpus entry
// source_repo: tradingview-custom-indicators
// source_path: tradingview-custom-indicators/movings/least_squares_moving_average.pine
// content_hash: 4133cae14b7ab277
// collected: 2026-07-27
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Least Squares Moving Average script may be freely distributed under the MIT license.
study("Least Squares Moving Average", shorttitle="LSMA", overlay=true)

length = input(title="Length", type=integer, minval=1, defval=14)
offset = input(title="Offset", type=integer, defval=0)
src = input(title="Source", type=source, defval=close)

plot(linreg(src, length, offset), title="LSMA", linewidth=2, color=#6d1e7f, transp=0)
