// set05 corpus entry
// source_repo: aceri-tradingview_pinescript
// source_path: aceri-tradingview_pinescript/RSI BUY Huobi 30m.txt
// content_hash: 43a5b54d27e165cb
// collected: 2026-07-27
//Created by Chris Moody on 8/8/2014 by Request for motcha1
//RSI Indicator with EMA of RSI for Signal
//Great Confirrming Signal for CM_Williams_Vix_Fix https://www.tradingview.com/v/og7JPrRA/
study(title="RSI_BUY", shorttitle="RSI_BUY_Huobi30m", overlay=false)
src = close, 
len = input(362, minval=1, title="RSI Length")
len2 = input(10, minval=1, title="LowerLine")
up = rma(max(change(src), 0), len)
down = rma(-min(change(src), 0), len)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))
emaRSI = ema(rsi,len2)

plot(rsi, title="RSI", style=line, linewidth=3, color=silver)
//plot(emaRSI, title="EMA of RSI", style=circles, linewidth=2, color=red)
//band1 = hline(80, title="Upper Line", linestyle=dashed, linewidth=3, color=red)
band0 = hline(52, title="Lower Line", linestyle=dashed, linewidth=3, color=lime)
//fill(band1, band0, color=purple, transp=90)
